### ISSUE TITLE
validatejs.org not displaying right on Safari

### ISSUE THREAD

**Issue by kenn** [wrapp-archive/validate.js#1]
The site http://validatejs.org doesn't look right with the latest Safari on OSX Mavericks.

Just wanted to mention real quick.

**Comment by ansman** [comment]
Awesome, thanks. It's been fixed now.

I had tried using [flexbox](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes) for the layouting but I guess it wasn't as ready as I had hoped.
I've switched back to good ol' `position: fixed`.
