### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by marfarma** [wrapp-archive/validate.js#10]
I've written an asyncValidate function that takes a callback to execute with the results of the validation.  It allows me to write custom validations, such as 'unique', 'exists' and 'omits' against a property value's presence in a datastore with an async api.

I wrote it using angularjs promises, but it could be modified to use [ES6-Promises shim](https://github.com/jakearchibald/ES6-Promises/blob/master/README.md) instead.  

If you'd like I could take a stab at adding it to the library with the shim and send a pull request.

**Comment by ansman** [comment]
Great suggestion, we should definitely implement this.

Let me think about this over the holidays, ok?

There is a couple of points we need to decide on:
- Should async validation be a separate function or not?
- Should we use promises only or support callbacks too?

**Comment by marfarma** [comment]
I think it would be better if it used the same function.  I didn't want to assume that it would be added to the library and didn't want to have to maintain a fork long term.

I use promises internally in the validate function, and take a callback.  Don't know why I didn't think of returning a promise directly.  _(off to refactor)_   It would be easy to return a promise if a callback was not provided.  Individual validation functions should return a value or a promise -- I don't see how callbacks would work there.  This is what I have, with discussion points in comments. 

At the bottom of the attr loop:

<pre>
                          error = validator.call(validator,
                                                 value,
                                                 validatorOptions,
                                                 attr,
                                                 attributes);
                          if (validate.isDefined(error)) {
                              // ideally validation functions would return {attr:attr, error:error} objects
                              // or a promise that resolved to same, and the if block would become
                              // promises.push($q.when(error));
                              // but that would be a breaking change.
                              if (validate.isString(error) || validate.isArray(error)){
                                  promises.push($q.when({attr:attr, error:error}));
                              } else {
                                  promises.push(error); // promises resolve to {attr:attr, error:error} objects
                              }
                          }
                         // if error is not a promise $q.when(error) resolves to the value immediately.  
                         // is there a risk if the caller is not expecting async behavior, when none of the
                         // validations return a promise?   
</pre>

and then, after the loop completes, wait for all the promises to resolve:

```
                  $q.all(promises).then(
                      function(data){
                          var errors = {};
                          var attr = null;
                          data.forEach(function(result) {
                              attr = result.attr;

                              // The validator is allowed to return a string or an array.
                              if (validate.isString(result.error)) result.error = [result.error];
                              if (result.error && result.error.length > 0) {
                                errors[attr] = (errors[attr] || []).concat(result.error);
                              }
                          });
                          errors = validate.fullMessages(errors, options);

                          // Return the errors if we have any

                          // can optionally return errors directly, return a promise, or via callback if provided
                          // decide if async results or direct return based on a config setting, rather than
                          // an additional parameter?

                          if (Object.keys(errors).length > 0) {
                              callback(errors,null);
                          } 
                          else {
                              callback(null,null);
                          }
                      },
                      function(error){

                          // TODO: should throw an exception, 
                          // this represents an unexpected error, not a validation failure

                          console.log("asyncValidate error:");
                          console.log(error);
                      }
                  );
```

**Comment by ansman** [comment]
Well, first of all I'd rather see that we use the error handler for failed validations rather than returning an error.  
This:

``` javascript
validate(constraints).then(handleSuccess, handleErrors);
```

is much cleaner than

``` javascript
validate(constraints).then(function(errors) {
  if (errors) handleErrors(errors)
  else handleSuccess();
});
```

Also, I think that we should be explicit in when async is being used and when it's not.  
The reason why is that I like the return type to be constant, either you always get an array (or `null`) back or always a promise.

Imagine working with a library that sometimes returns null, sometimes an array and sometimes a promise.  
Then you might forget to change your handler code and treat the promise an array.

Perhaps an option would be appropriate:

``` javascript
validate(constraints, {async: true});
```

But as I said, let me iron out the details during the next few days.

Thanks

**Comment by ansman** [comment]
@MarFarMa I'm almost done, I'll hopefully be done in a day or two.

Would you be willing to take a look at it when I'm done?

The current syntax looks like this:

``` javascript
validate.async(attributes, constraints, options).then(
  function() {
    // Validations passed
  },
  function(errors) {
    // Validations failed, errors is in the same format as returned by validate()
  }
);
```

Initially `Q`, `RSVP`, `When` and native promises are supported, jQuery will not be supported due to the lack of chaining.

**Comment by ansman** [comment]
@MarFarMa I've submitted a pull request here: #12 
Please take a look when you have a moment.
