### ISSUE TITLE
Support specifying dependencies between fields

### ISSUE THREAD

**Issue by ansman** [wrapp-archive/validate.js#13]
Being able to specify `OR`, `AND`, `XOR` between one or more fields would be useful.

Also being able to specify that one field requires another field but not vise versa would be useful.

**Comment by gaydenko** [comment]
Custom validation function has all attributes among parameters. So, say, I use them to add validation rules involving another fields (say, email2 field must be the same as email field): 

``` javascript
// options has: myName, thatName, thatKey 
validate.validators.match = function(value, options, key, attrs) {
    var that = attrs[options.thatKey];
    if ((value && that && value !== that) || (value && !that) || (!value && that))
        return 'Fields \"' + options.thatName + '\" and \"' + options.myName + '\" must be equal';
};
```

This is some kind of AND :) So, you are just saying about augmenting official rules set, aren't you?

**Comment by ansman** [comment]
@gaydenko The idea is for the constraints to be sharable between server and client, the options will be language specific.

So storing it in the options wouldn't really be an option (no pun intended).
