### ISSUE TITLE
Loading validate.js via AMD loading not working

### ISSUE THREAD

**Issue by ghost** [wrapp-archive/validate.js#15]
I am trying to load validate.js with the Dojo AMD Loader

**Comment by ghost** [comment]
Using this code:

```
define(['validate/validate'], function(validate) {
  console.debug(validate); // validate is '3'
});
```

**Comment by ghost** [comment]
the file is found (according to firebug) but the amd loader does not deliver the validate() function but the number 3.

**Comment by ansman** [comment]
Which version of DOJO are you using?

Also, please try this `console.log(arguments)`.

**Comment by ghost** [comment]
Hi ansman,
I am using dojo 1.9.2, I tried the same code above with `console.log(arguments)` and it will give an array with number 3 in it. I found the following statement on the dojo site:
- The Dojo Loader will also pass the number 3 to the callback in place of the module. 3 is the Dojo AMD loader code for attempting to load a non-module.

**Comment by ansman** [comment]
This works just fine for me:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
</head>
<body>
<script src="dojo.js"></script>
<script>
  require(['validate'], function(validate) {
    console.debug(validate);
  });
</script>
</body>
</html>
```

With the following file tree:

```
$ tree
.
├── dojo.js
├── index.html
└── validate.js

0 directories, 3 files
```

This was using DOJO <b>1.9.2</b> too.

**Comment by ghost** [comment]
I followed your test setup and added another
file `a.js` in the test directory:

```
define([
], function() {

    return 'hi';
});
```

For testing I used python simple webserver which
first I ran directly in the test directory. I `require` the
`validate.js` and `a.js` file which worked as expected.

```
require([ 'validate', 'a' ], function() {
    console.debug(arguments);
    // result: [function(), "hi"]
});
```

For the second run I moved up a directory and
again ran the webserver (My test directory is
named `test`). My `require` section now looks
like this:

```
require([ 'test/validate', 'test/a' ], function() {
    console.debug(arguments);
    // result: [undefined, "hi"]
});
```

Strangely enough it will resolve `a.js` but not
`validate.js` anymore. (Even though firebug tells
me that the `validate.js` was found and loaded).

**Comment by ansman** [comment]
This seems to be due a config issue in DOJO.
I don't know enough to know why it's behaving this way but this example seems to solve it for me:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
</head>
<body>
<script>
  var dojoConfig = {
    paths: {
      validate: "/test/validate"
    }
  };
</script>
<script src="dojo.js"></script>
<script>
  require(['validate'], function(validate) {
    console.debug(validate);
  });
</script>
</body>
</html>
```

Let me know if this doesn't work for you.

**Comment by ghost** [comment]
Your solution works and I will integrate validate.js
into my project as suggested, thanks for your help!

Still, it seems to me that something is not 100% correct
in how _validate_ implements AMD support.
In my project I use some other libraries for
which I didnt't have these kind of problems.

Here is a snippet of my _dojoConfig_:

``` javascript
dojoConfig = {

    packages: [
        // ...
        {
            name: 'validate',
            location: 'js/lib/validate'
        },
        {
            name: 'put-selector',
            location: 'js/lib/put-selector'
        }
        // ...
    ]
}
```

and a module that uses both of these libraries:

``` javascript

define([
    'put-selector/put',
    'validate/validate'
], function(put, validate) {

    console.debug(arguments);
    // result: [put(topReferenceElement), 3]

});
```

There seems to be a difference in how _put-selector_
and _validate_ implement AMD support.

**Comment by ansman** [comment]
hmm, that's strange.

If you find out why let me know by either making a pull request or reopen this issue.

Thanks!
