### ISSUE TITLE
Performance and Speed Issues

### ISSUE THREAD

**Issue by sansmischevia** [wrapp-archive/validate.js#17]
Noticed that a simple Object validation takes >40ms to perform (both async and sync):

Here is my constraint:

```
    name: {
      length: {
        minimum: 3,
        maximum: 40
      }
    }
```

Has anyone else experienced similar performance issues?

**Comment by ansman** [comment]
Which browser, OS etc?

For me it takes less than 1ms on Chrome/OSX

**Comment by sansmischevia** [comment]
This was in a node.js mocha test - i can try packaging something to show you. Any differences between browser and node implementation? It seems really odd to me as well.

**EDIT** - might be the promises library I was using "Q". Will try another and see if that helps.

**Comment by ansman** [comment]
Yeah, strange indeed, here's what I get:

```
$ node
> var validate = require("./validate.js");
undefined
> var constraints = {
...     name: {
.....       length: {
.......         minimum: 3,
.......         maximum: 40
.......       }
.....     }
... };
undefined
> var start = new Date(); validate({}, constraints); console.log(new Date() - start);
0
undefined
>
```

Please let me know what you find. If there anything I can do just let me know.
