### ISSUE TITLE
Abreviated notation for single field validation

### ISSUE THREAD

**Issue by franciscolourenco** [wrapp-archive/validate.js#21]
Would be nice be able to use an abbreviated form when you just need to validate a single field:

```
validate('string.to.be@validated.com', {email: true})
```

Is something like this currently possible?

**Comment by ansman** [comment]
I would think that something like this would do the trick:

``` javascript
validate.short = function(value, validators) {
  var attributes = {foo: value}
    , constraints = {foo: validators}
    , options = {fullMessages: false, flatten: true};
  return validate(attributes, constraints, options);
}
```

**Comment by franciscolourenco** [comment]
That seems to do the trick, thanks :)
Maybe something like this to keep the interface minimal?
https://github.com/aristidesfl/validate.js/commit/8aa45297d1846fd7688341c5b65df09ffad6d89e

**Comment by ansman** [comment]
See my comment in the PR
