### ISSUE TITLE
Returning original attributes from validator/promise

### ISSUE THREAD

**Issue by pstoica** [wrapp-archive/validate.js#25]
Hey, I just started reading the docs for this and it seems like a good validation solution in node!

I haven't started using it yet, but I do have one suggestion. Using validate.async uses Promises but kind of drops composition by default by returning undefined if there are no errors. I could see it being more useful for chaining by returning the original attributes, or rejecting otherwise. The workaround would be to manually create success callbacks that return attributes, which would be redundant.

Not sure if this would be a breaking change, but maybe it can be an option in validate.async? What are your thoughts?

**Comment by ansman** [comment]
So if I understand you correctly this is what you are looking for:

``` javascript
validate.async(attrs, constaints)
  .then(function(validatedAttrs) {
      console.log(attrs === validatedAttrs); // Logs true
    }, function(error) {
      // Do something
    });
```

This definitely sounds like a good idea! :)
